version: "3"

networks:
  simple:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      simple:
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.log-level=debug
      - --global.insecure
      - --global.disable-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --raft.in-memory
      - --plugins.ipam.static-ipv4=join-node=172.16.0.20/32
      - --plugins.ipam.static-ipv4=bootstrap-node=172.16.0.10/32
    ports:
      - 8443:8443
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
    hostname: join-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=bootstrap-node:8443
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
