version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24
          gateway: 10.30.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24

services:
  # Bootstrap/TURN Node

  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.30.0.1
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --global.primary-endpoint=10.30.0.1
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.ipv4-network=10.100.10.0/24
      - --raft.in-memory
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW"]

  site-1-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.30.0.2
      site-1:
    hostname: site-1-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --global.log-level=debug
      - --mesh.join-address=10.30.0.1:8443
      # TODO: Rendezvous can and should be derived from each node's public key
      - --mesh.libp2p-peers=site-2-peer=${RENDEZVOUS:-supersecret-webmesh-spot}
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW"]

  site-2-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.30.0.3
      site-2:
    hostname: site-2-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=10.30.0.1:8443
      # TODO: Same as above
      - --mesh.libp2p-peers=site-1-peer=${RENDEZVOUS:-supersecret-webmesh-spot}
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW"]
