version: "3"

networks:
  bootstrap:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  # Some random server that will serve the allowed-ids.txt file
  id-server:
    image: python:3.9
    networks:
      bootstrap:
        ipv4_address: 10.1.0.6
    entrypoint:
      - python
      - -m
      - http.server
      - --directory=/data
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./allowed-ids-http.txt:/data/allowed-ids.txt

  # A network leader that is trusting IDs in a local file and from the id-server
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      bootstrap:
        ipv4_address: 10.1.0.5
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --plugins.id-auth.id-files=/allowed-ids.txt,http://10.1.0.6/allowed-ids.txt
    volumes:
      - ./allowed-ids.txt:/allowed-ids.txt
    ports:
      - 8443:8443
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    depends_on:
      - id-server

  # Nodes that are connecting to the network leader

  node-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      bootstrap:
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=10.1.0.5:8443
      - --wireguard.key-file=/wireguard.key
      - --wireguard.key-rotation-interval=0
      - --auth.id-auth=true
    volumes:
      - ./node-1.key:/wireguard.key
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  node-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      bootstrap:
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=10.1.0.5:8443
      - --wireguard.key-file=/wireguard.key
      - --wireguard.key-rotation-interval=0
      - --auth.id-auth=true
    volumes:
      - ./node-2.key:/wireguard.key
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
