version: "3"

networks:
  simple:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          # Gateway is the same address as the host
          gateway: 10.1.0.1

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      simple:
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.log-level=debug
      - --global.disable-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --storage.in-memory
      - --plugins.test-plugin.remote.server=10.1.0.1:8081
      - --plugins.test-plugin.remote.insecure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
    hostname: join-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=bootstrap-node:8443
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
