version: "3"

networks:
  simple:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      simple:
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --raft.in-memory
      - --plugins.debug.listen-address=:6060
      - --plugins.debug.enable-db-querier=true
    ports:
      - 6060:6060
      - 8443:8443
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
    hostname: join-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-as-observer
      - --mesh.join-address=bootstrap-node:8443
      - --mesh.max-join-retries=15
      - --plugins.debug.listen-address=:6061
      - --plugins.debug.enable-db-querier=true
    restart: on-failure
    ports:
      - 6061:6061
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
