version: "3"

networks:
  simple:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
        - subnet: 2001:db8:3200::/64
          gateway: 2001:db8:3200::1

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
        ipv4_address: 10.1.0.2
        ipv6_address: 2001:db8:3200::2
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      # To disable TLS over the gRPC server, set --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --storage.in-memory
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    ports:
      - "8443:8443"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
        ipv4_address: 10.1.0.3
        ipv6_address: 2001:db8:3200::3
    hostname: join-node
    entrypoint:
      - /webmesh-node
      # The bootstrap-node will run with a self-signed certificate by default.
      - --global.insecure-skip-verify
      - --mesh.join-addresses=bootstrap-node:8443
    restart: on-failure
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
