version: "3"

networks:
  bootstrap:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      bootstrap:
        ipv4_address: 10.1.0.5
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --plugins.basic-auth.htpasswd-file=/etc/htpasswd
    ports:
      - 8443:8443
    volumes:
      - ./htpasswd:/etc/htpasswd
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      bootstrap:
    hostname: join-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.disable-ipv6
      - --mesh.join-address=10.1.0.5:8443
      - --auth.basic.username=join-node
      - --auth.basic.password=dobad
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
