name: Tests and Build
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  ALPINE_IMAGE_NAME: ghcr.io/webmeshproj/node
  DISTROLESS_IMAGE_NAME: ghcr.io/webmeshproj/node-distroless
  GO_VERSION: "1.21"
  GOLANGCI_LINT_VERSION: v1.54.2
  DOCKER_PLATFORMS: linux/amd64,linux/arm64,linux/arm,linux/386,linux/ppc64le,linux/s390x
  CACHE_DEP_PATH: go.sum
  LINT_TIMEOUT: 10m
  WEBMESH_BADGER_MAX_GOROUTINES: 8
  BUILD_PARALLELISM: 8
  TEST_PARALLELISM: 8
  # Lower test parallelism to avoid OOM on Windows
  WIN_TEST_PARALLELISM: 4
  COSIGN_EXPERIMENTAL: 1

jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Run Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout ${{ env.LINT_TIMEOUT }}

  tests:
    name: Unit Tests
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Setup Test Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-unittests-go-${{ env.GO_VERSION }}-${{ hashFiles(env.CACHE_DEP_PATH) }}
          restore-keys: ${{ runner.os }}-unittests-go-${{ env.GO_VERSION }}-
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build

      - name: Run Unit Tests
        shell: bash
        env:
          TEST_PARALLEL: ${{ matrix.os == 'windows-latest' && env.WIN_TEST_PARALLELISM || env.TEST_PARALLELISM }}
          RICHGO_FORCE_COLOR: 1
        run: |
          set -eo pipefail
          make ci-test | xargs -IL date +"[%Y-%m-%d %H:%M:%S]: L"

  build-binaries:
    name: Build Binary Artifacts
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Setup Build Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-binaries-go-${{ env.GO_VERSION }}-${{ hashFiles(env.CACHE_DEP_PATH) }}
          restore-keys: ${{ runner.os }}-binaries-go-${{ env.GO_VERSION }}-
          path: |
            ~/go/pkg
            ~/.cache/go-build

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Run Snapshot Release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          version: latest
          args: release --snapshot --clean --fail-fast --parallelism=${{ env.BUILD_PARALLELISM }}

      - name: Run Release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        with:
          version: latest
          args: release --clean --fail-fast --parallelism=${{ env.BUILD_PARALLELISM }}

  build-containers:
    name: Build Containers
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: false

      - name: Setup Build Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-containers-go-${{ env.GO_VERSION }}-${{ hashFiles(env.CACHE_DEP_PATH) }}
          restore-keys: ${{ runner.os }}-containers-go-${{ env.GO_VERSION }}-
          path: |
            ~/go/pkg
            ~/.cache/go-build

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute Image Tags
        shell: bash
        id: image-tags
        run: |
          ALPINE_IMAGES="${{ env.ALPINE_IMAGE_NAME }}:latest,${{ env.ALPINE_IMAGE_NAME }}:${{ github.sha }}"
          DISTROLESS_IMAGES="${{ env.DISTROLESS_IMAGE_NAME }}:latest,${{ env.DISTROLESS_IMAGE_NAME }}:${{ github.sha }}"
          if [[ ${{ github.ref }} =~ ^refs/tags/v.* ]] ; then
              ALPINE_IMAGES+=",${{ env.ALPINE_IMAGE_NAME }}:${{ github.ref_name }}"
              DISTROLESS_IMAGES+=",${{ env.DISTROLESS_IMAGE_NAME }}:${{ github.ref_name }}"
          fi
          echo "alpine-images=${ALPINE_IMAGES}" >> "${GITHUB_OUTPUT}"
          echo "distroless-images=${DISTROLESS_IMAGES}" >> "${GITHUB_OUTPUT}"

      - name: Run Snapshot Container Release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          version: latest
          args: build --snapshot --clean --id node-docker-linux --parallelism=${{ env.BUILD_PARALLELISM }}

      - name: Run Container Release
        uses: goreleaser/goreleaser-action@v5
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          version: latest
          args: build --clean --id node-docker-linux --parallelism=${{ env.BUILD_PARALLELISM }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Alpine Container Images
        uses: docker/build-push-action@v5
        id: alpine-build
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-tags.outputs.alpine-images }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          build-args: PREFIX=node-docker-linux

      - name: Build Distroless Container Images
        uses: docker/build-push-action@v5
        id: distroless-build
        with:
          context: .
          file: Dockerfile.distroless
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-tags.outputs.distroless-images }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          build-args: PREFIX=node-docker-linux

      - name: Sign Container Images
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cosign sign --yes --recursive ${{ env.ALPINE_IMAGE_NAME }}@${{ steps.alpine-build.outputs.digest }}
          cosign sign --yes --recursive ${{ env.DISTROLESS_IMAGE_NAME }}@${{ steps.distroless-build.outputs.digest }}
